export const SITE_URL = "https://kevinliu.biz";

export const SITE_TITLE =
  "Kevin Liu — Engineer, Designer & Builder | Princeton CS '28";

export const SITE_DESCRIPTION =
  "Kevin Liu is a Founding Engineer at Dedalus Labs (YC S25) and a Princeton CS student building production agent infrastructure, expressive interfaces, and browser games. Explore selected work and play PortfolioMon, his archived Pokemon-inspired portfolio battle game.";

export const OG_IMAGE = `${SITE_URL}/images/kevin_powerlifting_bw.png`;

// Name variants, misspellings, and phonetic near-misses people actually search
const NAME_VARIANTS = [
  "Kevin Liu",
  "kevin liu",
  "Kevin B Liu",
  "Kevin Bowen Liu",
  "K. Bowen Liu",
  "Keven Liu",
  "Kevn Liu",
  "Kelvin Liu",
  "Kevin Lui",
  "Kevin Lue",
  "Kevin Lieu",
  "Kevim Liu",
  "Keivn Liu",
  "Kevin Liw",
  "Kevin Luu",
  "Kenvin Liu",
  "Kevn Lui",
  "Kevin-Liu",
  "KevinLiu",
  "kevinliu",
  "kevskgs",
  "@kevskgs",
  "Kevin Liu 01",
  "Kevin-Liu-01",
];

// Princeton and education variants
const PRINCETON_VARIANTS = [
  "Kevin Liu Princeton",
  "Kevin Liu Princeton University",
  "Kevin Liu Princeton CS",
  "Kevin Liu Princeton computer science",
  "Kevin Liu Princeton 2028",
  "Kevin Liu Princeton '28",
  "Princeton CS Kevin Liu",
  "Princeton developer Kevin Liu",
  "Princeton software engineer",
  "Princeton CS student developer",
  "Princeton CS 2028",
  "Princeton University developer",
  "Princeton University CS student",
  "Princeton University software engineer",
  "Princeton University AI engineer",
  "Princeton BSE computer science",
  "Princeton class of 2028 developer",
  "Princeton class of 2028 CS",
  "Princeton NJ developer",
  "Princeton New Jersey software engineer",
  "Princeton computer science portfolio",
  "Princeton hackathon developer",
  "Princeton engineer",
  "Princeton student portfolio",
  "Princeton CS student projects",
  "Princeton University Class of 2028",
  "Princeton University undergraduate CS",
  "High Technology High School Kevin Liu",
  "HTHS Kevin Liu",
  "Monmouth County developer",
];

// Professional identity and role keywords
const PROFESSIONAL_KEYWORDS = [
  "full-stack developer",
  "fullstack developer",
  "full stack developer",
  "AI engineer",
  "software engineer",
  "software developer",
  "web developer",
  "frontend developer",
  "backend developer",
  "machine learning engineer",
  "React developer",
  "Next.js developer",
  "TypeScript developer",
  "Python developer",
  "Node.js developer",
  "AI researcher",
  "computer science student",
  "CS student developer",
  "gen Z developer",
  "young software engineer",
  "student developer portfolio",
  "founding engineer",
  "startup engineer",
  "Y Combinator engineer",
  "YC engineer",
  "YC S25",
  "Y Combinator S25 engineer",
];

// Company and work experience keywords
const WORK_KEYWORDS = [
  "Kevin Liu Amazon",
  "Kevin Liu Bloomberg",
  "Kevin Liu AT&T",
  "Kevin Liu ATT Labs",
  "Kevin Liu AT&T Labs Research",
  "Kevin Liu Dedalus",
  "Kevin Liu Dedalus Labs",
  "Kevin Liu Sevenfold",
  "Kevin Liu Sevenfold AI",
  "Kevin Liu Johns Hopkins",
  "Kevin Liu Y Combinator",
  "Kevin Liu YC",
  "Amazon SDE intern",
  "Bloomberg software engineering intern",
  "AT&T Labs AI research intern",
  "Dedalus Labs founding engineer",
  "Sevenfold AI founding engineer",
  "Johns Hopkins uCredit",
  "Amazon FBA Inventory",
  "Bloomberg Financial Instruments",
  "Bloomberg Core Products",
];

// Social media and online presence keywords
const SOCIAL_KEYWORDS = [
  "Kevin Liu GitHub",
  "Kevin Liu LinkedIn",
  "Kevin Liu Twitter",
  "Kevin Liu X",
  "Kevin Liu @kevskgs",
  "kevskgs Twitter",
  "kevskgs X",
  "@kevskgs",
  "Kevin-Liu-01 GitHub",
  "kevin-liu-princeton LinkedIn",
  "Kevin Liu Devpost",
  "Kevin Liu tech blog",
  "Kevin Liu software blog",
  "kevinliu.biz",
  "kevin-liu.tech",
  "Kevin Liu website",
  "Kevin Liu personal site",
  "Kevin Liu online portfolio",
  "Kevin Liu developer profile",
];

// Project and portfolio keywords
const PROJECT_KEYWORDS = [
  "PortfolioMon Showdown",
  "Pokemon Showdown portfolio",
  "Pokémon Showdown developer portfolio",
  "interactive developer portfolio",
  "gamified portfolio",
  "creative developer portfolio",
  "unique developer portfolio",
  "best developer portfolio",
  "best CS student portfolio",
  "best Princeton portfolio",
  "AI projects portfolio",
  "machine learning projects",
  "Dedalus AI SDK",
  "Dedalus MCP",
  "Dedalus Labs AI agents",
  "Sevenfold research",
  "Sevenfold AI workspace",
  "Lumachor context engine",
  "Lumachor AI",
  "Loop",
  "Loop operator desk",
  "Loop agent skills",
  "looooop.dev",
  "agent skills auto-refresh",
  "Sigil UI",
  "Sigil UI design system",
  "agent-first design system",
  "create-sigil-app",
  "design tokens system",
  "050525 Dedalus birthday",
  "050525 terminal experience",
  "Princeton Tower Defense",
  "Princeton Tower Defense game",
  "RecyclAIble PennApps",
  "RecyclAIble smart recycling",
  "HD Transcribe Huntingtons",
  "HD Transcribe speech model",
  "SnellTech eye exam",
  "ApneaAlert sleep apnea",
  "LetMeCook AI recipe",
  "Podium hackathon judging",
  "HackPrinceton website",
  "HackPrinceton developer",
  "OMMC math competition",
  "OMMC official",
  "Online Monmouth Math Competition",
  "EditorGPT code review",
  "AdventureGPT story",
  "Balladeer study guide",
  "Splitway expense tracker",
  "CompassUSA immigrant tool",
  "PawPointClicker Princeton",
  "Lootbox Simulator game",
  "Enkrateia GPT",
  "Satellite Crafter game",
  "PlantSTEM education",
  "Iron Triangle history",
  "OMMC Atlas database",
];

// Hackathon and achievement keywords
const ACHIEVEMENT_KEYWORDS = [
  "hackathon winner",
  "PennApps winner",
  "PennApps XXIII winner",
  "PennApps XXIII 1st place",
  "PennApps hardware winner",
  "HackPrinceton organizer",
  "HackPrinceton lead developer",
  "hackathon organizer Princeton",
  "OMMC co-founder",
  "OMMC founder",
  "math competition founder",
  "30+ projects developer",
  "prolific developer",
  "student hackathon winner",
];

// Technology and skill keywords for search matching
const TECH_KEYWORDS = [
  "MCP AI agents",
  "Model Context Protocol developer",
  "LLM integration developer",
  "GPT-4 projects",
  "Claude AI developer",
  "AI agent SDK",
  "RAG developer",
  "vector embeddings",
  "computer vision developer",
  "OpenCV developer",
  "NLP developer",
  "speech recognition AI",
  "React Next.js TypeScript",
  "tRPC developer",
  "PostgreSQL Firebase MongoDB",
  "Prisma ORM",
  "Tailwind CSS developer",
  "Framer Motion animations",
  "Vercel deployment",
  "Docker developer",
  "GraphQL REST API",
  "full-stack web development",
  "game developer browser games",
  "health tech developer",
  "hardware IoT developer",
  "wearable technology developer",
];

// Disambiguation — there are many "Kevin Liu"s; these help search engines identify the right one
const DISAMBIGUATION_KEYWORDS = [
  "Kevin Liu developer not Kevin Liu journalist",
  "Kevin Liu Princeton not Kevin Liu Stanford",
  "Kevin Liu software engineer kevinliu.biz",
  "Kevin Liu computer science Princeton 2028",
  "Kevin Liu who built Dedalus",
  "Kevin Liu who built PortfolioMon Showdown",
  "Kevin Liu PennApps XXIII winner",
  "Kevin Liu Amazon Bloomberg AT&T intern",
  "Kevin Liu HackPrinceton organizer",
  "Kevin Liu OMMC founder",
  "Kevin Liu AI engineer Y Combinator",
  "Kevin Liu from New Jersey",
  "Kevin Liu Monmouth County",
  "Kevin Liu kevin-liu.tech",
  "the Kevin Liu with the Pokemon portfolio",
];

export const KEYWORDS = [
  ...NAME_VARIANTS,
  ...PRINCETON_VARIANTS,
  ...PROFESSIONAL_KEYWORDS,
  ...WORK_KEYWORDS,
  ...SOCIAL_KEYWORDS,
  ...PROJECT_KEYWORDS,
  ...ACHIEVEMENT_KEYWORDS,
  ...TECH_KEYWORDS,
  ...DISAMBIGUATION_KEYWORDS,
].join(", ");

export const SOCIAL_LINKS = {
  github: "https://github.com/Kevin-Liu-01",
  linkedin: "https://www.linkedin.com/in/kevin-liu-princeton/",
  x: "https://x.com/kevskgs",
  devpost: "https://devpost.com/Kevin-Liu-01",
  alternate: "https://www.kevin-liu.tech",
  email: "k.bowen.liu@gmail.com",
} as const;
